Name: Daniel Kofi Edem Avuworda
Program: NextGenLearners Data Science Internship
Week: 1
Project: Cleaning and Exploring the Applicant Dataset
Objective: The Objective of this project is Practice data cleaning, wrangling, and basic exploration using Pandas.The single most important skill in data science, since real-world data is almost never clean. The project will address missing value, duplicate records, inconsistent text formatting, and incorrect data types.

In [194]:
#Importing Tools to Use For The Project
import pandas as pd
import numpy as np

In [195]:
#Uploading the dataset
from google.colab import files

uploaded = files.upload()

Saving applicants.csv to applicants (6).csv

In [196]:
#Loading the dataset
df = pd.read_csv('applicants.csv') #df is the name of my DataFrame

In [197]:
#Verifying that dataset has been loaded
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ama Mensah,amamensah1@example.com,0208424518,Cybersecurity,University for Development Studies,29/04/2026,Under Review
1,Adwoa Frimpong,adwoafrimpong2@example.com,0207733656,UI/UX Design,"University of Professional Studies, Accra",21/01/2026,Under Review
2,Yaw Addo,yawaddo3@example.com,0208174426,UI/UX Design,University of Ghana,16/04/2026,Rejected
3,Ali Khan,ericnkrumah4@example.com,0207564615,Data Analytics,"University of Education, Winneba",08/01/2026,Under Review
4,Joyce Baah,joycebaah5@example.com,0244279908,Web Development,University for Development Studies,26/06/2026,Under Review

In [198]:
#Checking the number of rows and columns of the dataset
df.shape

(100, 7)

In [199]:
#Examining the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    95 non-null     object
 1   Email             94 non-null     object
 2   Phone             96 non-null     object
 3   Domain Applied    97 non-null     object
 4   University        97 non-null     object
 5   Application Date  98 non-null     object
 6   Status            98 non-null     object
dtypes: object(7)
memory usage: 5.6+ KB

In [200]:
#Counting the missing values
df.isnull().sum()

Applicant Name      5
Email               6
Phone               4
Domain Applied      3
University          3
Application Date    2
Status              2
dtype: int64

In [201]:
#Counting the exact duplicate rows
df.duplicated().sum()

np.int64(1)

In [202]:
#Identifying the inconsistent categories
print(df['Domain Applied'])

0       Cybersecurity
1        UI/UX Design
2        UI/UX Design
3      Data Analytics
4     Web Development
           ...
95       UI/UX Design
96    Web Development
97      Cybersecurity
98      Cybersecurity
99       UI/UX Design
Name: Domain Applied, Length: 100, dtype: object

#Initial Dataset Assessment

# The applicant dataset was examined before cleaning to understand its structure and identify potential data-quality problems.

The initial assessment included:

Checking the number of rows and columns.

Inspecting the first five records.

Examining column names and data types.

Counting missing values in each column.

Identifying exact duplicate records.

Examining the distinct values in the Domain Applied and Status columns.


The results of this assessment will guide the cleaning decisions made in the subsequent stages.
# The Dataset has 100 rows amd 7 columns. Applicant Name has 5 missiing values, Email has 6 missing values, Phone nas 4 missing values, Domain applied has 3 missing values, University has 3 missing values, Application Date and Status has 2 missing values.

In [203]:
#Checking for missing values again
df.isnull().sum()

Applicant Name      5
Email               6
Phone               4
Domain Applied      3
University          3
Application Date    2
Status              2
dtype: int64

HANDLING MISSING VALUES(COLUMN BY COLUMN, WITH JUSTIFICATION)
Since there is no "correct" way to handle missing data, the right choice depends on the column and what the data is used for.

In [204]:
#Removing records without applicat names
df = df.dropna(subset=['Applicant Name'])

In [205]:
df = df.dropna(subset=['Email'])

In [206]:
#Filling missing university information
df['University'] = df['University'].fillna('Not Specified')

In [207]:
#Filling missing application statuses
df['Status'] = df['Status'].fillna('Under Review')

In [208]:
#Rechecking the missing values. This will review the results to see which missing values remain
df.isnull().sum()

Applicant Name      0
Email               0
Phone               2
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

In [209]:
#Removing missing values for Phone numbers and Application date
df=df.dropna(subset=['Phone'])

In [210]:
#Removing missing values for Application date
df=df.dropna(subset=['Application Date'])

In [211]:
df.isnull().sum()

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

## Handling Missing Values

Missing values were examined separately for each column.

1. **Applicant Name:** Records without applicant names were removed because the missing identifying information limited their usefulness for applicant follow-up.
2. **Email:** Missing email addresses were handled according to the selected retention policy, considering the importance of email for communication.
3. **University:** Missing values were replaced with "Not Specified" to retain otherwise useful applicant records.
4. **Status:** Missing values were replaced with "Under Review", following the task guide's suggested default. This assumption will be documented when interpreting the results.

The missing-value counts were checked again after cleaning to assess the effectiveness of these actions.

In [212]:
# Check exact duplicates first
df.duplicated().sum()

np.int64(1)

In [213]:
#Removing exact duplicates
df = df.drop_duplicates()

In [214]:
df['Email'] = df['Email'].str.strip().str.lower()

In [215]:
#checking for duplicate Email addresses
df[df.duplicated(subset=['Email'], keep=False)].sort_values('Email')

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
49,Joseph Tetteh,josephtetteh52@example.com,0579024620,Cybersecurity,University of Ghana,21/02/2026,Rejected
51,Joseph Tetteh,josephtetteh52@example.com,0595360071,UI/UX Design,"University of Professional Studies, Accra",09/01/2026,Under Review
30,Peter Ofori,peterofori32@example.com,0568976603,Data Science,"University of Professional Studies, Accra",05/07/2026,Selected
31,Peter Ofori,peterofori32@example.com,0203666555,Data Science,University of Ghana,30/07/2026,selected

In [216]:
#Remove duplicate applications by Email
df = df.drop_duplicates(subset=['Email'], keep='first')

In [217]:
#Verifying the results
print("Exact duplicate rows:", df.duplicated().sum())

print(
    "Duplicate email addresses:",
    df['Email'].dropna().duplicated().sum()
)

Exact duplicate rows: 0
Duplicate email addresses: 0

Suppose the Domain Applied column contains:
web dev
WEB DEV
Web Development
web development
Data science
DATA SCIENCE

In [218]:
#Removing unnecessary space
text_columns = ['Applicant Name','Email','Phone','Domain Applied','University','Status']

In [219]:
#Removing leading and trailing spaces
for col in text_columns:
    df[col] = df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x)

In [220]:
#standardize applicant names
df['Applicant Name'] = df['Applicant Name'].str.title()

In [221]:
#Standardize the five domain categories
print(df['Domain Applied'].value_counts(dropna=False))

Domain Applied
Data Analytics     19
Data Science       17
UI/UX Design       16
Web Development    16
Cybersecurity      15
web dev             1
WEB DEV             1
Name: count, dtype: int64

In [222]:
#Standardizing application status
df['Status'] = df['Status'].str.strip().str.title()
print(df['Status'].value_counts(dropna=False))

Status
Selected        33
Under Review    30
Rejected        22
Name: count, dtype: int64

In [223]:
#Correcting Date Formatting
#Convert application dates
df['Application Date'].head(10)

0     29/04/2026
1     21/01/2026
2     16/04/2026
3     08/01/2026
4     26/06/2026
6     04/06/2026
10    29/03/2026
11    02/05/2026
12    15/06/2026
13    17/03/2026
Name: Application Date, dtype: object

In [224]:
df['Application Date'] = pd.to_datetime(df['Application Date'],errors='coerce',dayfirst=True)

In [225]:
df['Application Date'].dtype

dtype('<M8[ns]')

In [226]:
#Checking missing new dates
df['Application Date'].isnull().sum()

np.int64(0)

In [227]:
#Cleaning Phone number
df['Phone'] = (df['Phone'].astype('string').str.replace(r'[\s-]+', '', regex=True))

In [228]:
#verifying changes
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    85 non-null     object
 1   Email             85 non-null     object
 2   Phone             85 non-null     string
 3   Domain Applied    85 non-null     object
 4   University        85 non-null     object
 5   Application Date  85 non-null     datetime64[ns]
 6   Status            85 non-null     object
dtypes: datetime64[ns](1), object(5), string(1)
memory usage: 5.3+ KB

In [229]:
#Performing the final data quality checks
print("Final dataset shape:", df.shape)
#Ckecking if there are still som,e missing values
print(df.isnull().sum())
#Checking for if there are still some duplicates
print("Exact duplicates:", df.duplicated().sum())
#Checking for duplicate Emails
print("Duplicate emails:",df['Email'].dropna().duplicated().sum())
#Checking for domain categories
print(df['Domain Applied'].value_counts(dropna=False))
print(df['Domain Applied'].unique())
#Checking the final data types
df.info()

Final dataset shape: (85, 7)
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64
Exact duplicates: 0
Duplicate emails: 0
Domain Applied
Data Analytics     19
Data Science       17
UI/UX Design       16
Web Development    16
Cybersecurity      15
web dev             1
WEB DEV             1
Name: count, dtype: int64
['Cybersecurity' 'UI/UX Design' 'Data Analytics' 'Web Development'
 'Data Science' 'web dev' 'WEB DEV']
<class 'pandas.core.frame.DataFrame'>
Index: 85 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    85 non-null     object
 1   Email             85 non-null     object
 2   Phone             85 non-null     string
 3   Domain Applied    85 non-null     object
 4   University        85 non-null     object
 5   Application Date  85 non-null     datetime64[ns]
 6   Status            85 non-null     object
dtypes: datetime64[ns](1), object(5), string(1)
memory usage: 5.3+ KB

In [230]:
#Previewing the Final cleaned data
df.head(10)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ama Mensah,amamensah1@example.com,0208424518,Cybersecurity,University for Development Studies,2026-04-29,Under Review
1,Adwoa Frimpong,adwoafrimpong2@example.com,0207733656,UI/UX Design,"University of Professional Studies, Accra",2026-01-21,Under Review
2,Yaw Addo,yawaddo3@example.com,0208174426,UI/UX Design,University of Ghana,2026-04-16,Rejected
3,Ali Khan,ericnkrumah4@example.com,0207564615,Data Analytics,"University of Education, Winneba",2026-01-08,Under Review
4,Joyce Baah,joycebaah5@example.com,0244279908,Web Development,University for Development Studies,2026-06-26,Under Review
6,Esther Kwarteng,estherkwarteng7@example.com,0508358723,Data Analytics,Kwame Nkrumah University of Science and Techno...,2026-06-04,Rejected
10,Akosua Osei,akosuaosei11@example.com,0504961730,UI/UX Design,University for Development Studies,2026-03-29,Selected
11,Benjamin Arthur,benjaminarthur12@example.com,0250402191,Cybersecurity,University of Ghana,2026-05-02,Under Review
12,Isaac Opoku,isaacopoku13@example.com,0241234567,Data Science,University for Development Studies,2026-06-15,Under Review
13,Priscilla Aidoo,priscillaaidoo14@example.com,0263974543,Web Development,"University of Education, Winneba",2026-03-17,Under Review

In [231]:
#Exporting the final cleaned CSV file
df.to_csv('applicants_cleaned.csv', index=False)

# Data Quality Summary

## 1. Starting Dataset

The original dataset contained 100 rows and 7 columns.

## 2. Data-Quality Issues Identified

The initial assessment identified the following issues:

* Missing values in one or more columns.
* Exact duplicate records and/or repeated email addresses.
* Inconsistent spelling, capitalization, and spacing in text fields.
* Inconsistent date formats.
* Inconsistent phone-number formatting.
* Other issues identified during the initial assessment.

## 3. Cleaning Actions Taken

The following actions were performed using Python and Pandas:

* Removed records with missing applicant names, based on the selected cleaning policy.
* Handled missing email addresses according to the documented retention policy.
* Replaced missing university information with "Not Specified".
* Replaced missing application statuses with "Under Review", following the task guide.
* Removed confirmed exact duplicates and duplicate applications according to the selected rules.
* Standardized applicant names, email addresses, domain categories, and application statuses.
* Converted application dates to a datetime format and investigated dates that could not be parsed.
* Removed spaces and dashes from phone numbers.
* Rechecked missing values, duplicate records, domain categories, and data types.

## 4. Final Dataset

The cleaned dataset contains 85 rows and 7 columns.

The final validation checks showed:

* Exact duplicate rows: 1.
* Duplicate email addresses: 2.
* Missing values by column: 25.

## 5. Conclusion

The applicant dataset was examined and cleaned using a reproducible Python workflow. The cleaning process addressed the data-quality issues identified during the initial assessment. The final validation results were used to determine whether the dataset met the assignment's requirements.

The cleaned CSV file was exported for further analysis, and the notebook documents the procedures and decisions made throughout the process.

In [232]:
#Downloading the final file from google colab
from google.colab import files

files.download('applicants_cleaned.csv')